/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    alternativePages: AlternativePage;
    ethnographicItems: EthnographicItem;
    maps: Map;
    manuscripts: Manuscript;
    intelligence_reports: IntelligenceReport;
    ethnography_and_archaeology: EthnographyAndArchaeology;
    government_reports: GovernmentReport;
    alternative_heritages: AlternativeHeritage;
    alternative_archival_heritages: AlternativeArchivalHeritage;
    photos: Photo;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    alternativePages: AlternativePagesSelect<false> | AlternativePagesSelect<true>;
    ethnographicItems: EthnographicItemsSelect<false> | EthnographicItemsSelect<true>;
    maps: MapsSelect<false> | MapsSelect<true>;
    manuscripts: ManuscriptsSelect<false> | ManuscriptsSelect<true>;
    intelligence_reports: IntelligenceReportsSelect<false> | IntelligenceReportsSelect<true>;
    ethnography_and_archaeology: EthnographyAndArchaeologySelect<false> | EthnographyAndArchaeologySelect<true>;
    government_reports: GovernmentReportsSelect<false> | GovernmentReportsSelect<true>;
    alternative_heritages: AlternativeHeritagesSelect<false> | AlternativeHeritagesSelect<true>;
    alternative_archival_heritages: AlternativeArchivalHeritagesSelect<false> | AlternativeArchivalHeritagesSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  internalName: string;
  slug: string;
  pageSection?: Section;
  parent?: (number | null) | Page;
  breadcrumbs?:
    | {
        doc?: (number | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Section".
 */
export interface Section {
  layout?:
    | (
        | {
            objectName?: string | null;
            localName?: string | null;
            accession?: string | null;
            accessionNumber?: string | null;
            image?: (number | null) | Media;
            location?: string | null;
            aquisition?: string | null;
            production?: string | null;
            height?: string | null;
            width?: string | null;
            breadth?: string | null;
            length?: string | null;
            weight?: string | null;
            circumference?: string | null;
            description?: string | null;
            provenance?: string | null;
            entry?: string | null;
            staff?: string | null;
            file?: (number | null) | Media;
            period?: string | null;
            photographer?: string | null;
            keyword?: string | null;
            identifiers?: string | null;
            slug?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alternativeFile';
          }
        | {
            NAHA?: string | null;
            author?: string | null;
            objectType?: string | null;
            ethnicityGroup?: string | null;
            image?: (number | null) | Media;
            artist?: string | null;
            geographicOrigin?: string | null;
            provenance?: string | null;
            entry?: string | null;
            staff?: string | null;
            file?: (number | null) | Media;
            identifiers?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'alternativeArchivalFile';
          }
      )[]
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternativePages".
 */
export interface AlternativePage {
  id: number;
  internalName: string;
  slug: string;
  pageSection?: Section;
  ethnographicItems?: (number | EthnographicItem)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ethnographicItems".
 */
export interface EthnographicItem {
  id: number;
  objectName: string;
  localName?: string | null;
  accession?: string | null;
  accessionNumber?: string | null;
  image?: (number | null) | Media;
  location?: string | null;
  aquisition?: string | null;
  production?: string | null;
  height?: string | null;
  width?: string | null;
  breadth?: string | null;
  length?: string | null;
  weight?: string | null;
  circumference?: string | null;
  description?: string | null;
  provenance?: string | null;
  ethnicity?: string | null;
  geographicOrigin?: string | null;
  identifiers?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps".
 */
export interface Map {
  id: number;
  image?: (number | null) | Media;
  file?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuscripts".
 */
export interface Manuscript {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence_reports".
 */
export interface IntelligenceReport {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ethnography_and_archaeology".
 */
export interface EthnographyAndArchaeology {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government_reports".
 */
export interface GovernmentReport {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternative_heritages".
 */
export interface AlternativeHeritage {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternative_archival_heritages".
 */
export interface AlternativeArchivalHeritage {
  id: number;
  internalName: string;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  image?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: number | Page;
      }
    | {
        relationTo: 'alternativePages';
        value: number | AlternativePage;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'alternativePages';
        value: number | AlternativePage;
      } | null)
    | ({
        relationTo: 'ethnographicItems';
        value: number | EthnographicItem;
      } | null)
    | ({
        relationTo: 'maps';
        value: number | Map;
      } | null)
    | ({
        relationTo: 'manuscripts';
        value: number | Manuscript;
      } | null)
    | ({
        relationTo: 'intelligence_reports';
        value: number | IntelligenceReport;
      } | null)
    | ({
        relationTo: 'ethnography_and_archaeology';
        value: number | EthnographyAndArchaeology;
      } | null)
    | ({
        relationTo: 'government_reports';
        value: number | GovernmentReport;
      } | null)
    | ({
        relationTo: 'alternative_heritages';
        value: number | AlternativeHeritage;
      } | null)
    | ({
        relationTo: 'alternative_archival_heritages';
        value: number | AlternativeArchivalHeritage;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  internalName?: T;
  slug?: T;
  pageSection?: T | SectionSelect<T>;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "Section_select".
 */
export interface SectionSelect<T extends boolean = true> {
  layout?:
    | T
    | {
        alternativeFile?:
          | T
          | {
              objectName?: T;
              localName?: T;
              accession?: T;
              accessionNumber?: T;
              image?: T;
              location?: T;
              aquisition?: T;
              production?: T;
              height?: T;
              width?: T;
              breadth?: T;
              length?: T;
              weight?: T;
              circumference?: T;
              description?: T;
              provenance?: T;
              entry?: T;
              staff?: T;
              file?: T;
              period?: T;
              photographer?: T;
              keyword?: T;
              identifiers?: T;
              slug?: T;
              id?: T;
              blockName?: T;
            };
        alternativeArchivalFile?:
          | T
          | {
              NAHA?: T;
              author?: T;
              objectType?: T;
              ethnicityGroup?: T;
              image?: T;
              artist?: T;
              geographicOrigin?: T;
              description?: T;
              provenance?: T;
              entry?: T;
              staff?: T;
              file?: T;
              identifiers?: T;
              id?: T;
              blockName?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternativePages_select".
 */
export interface AlternativePagesSelect<T extends boolean = true> {
  internalName?: T;
  slug?: T;
  pageSection?: T | SectionSelect<T>;
  ethnographicItems?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ethnographicItems_select".
 */
export interface EthnographicItemsSelect<T extends boolean = true> {
  objectName?: T;
  localName?: T;
  accession?: T;
  accessionNumber?: T;
  image?: T;
  location?: T;
  aquisition?: T;
  production?: T;
  height?: T;
  width?: T;
  breadth?: T;
  length?: T;
  weight?: T;
  circumference?: T;
  description?: T;
  provenance?: T;
  ethnicity?: T;
  geographicOrigin?: T;
  identifiers?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "maps_select".
 */
export interface MapsSelect<T extends boolean = true> {
  image?: T;
  file?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manuscripts_select".
 */
export interface ManuscriptsSelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "intelligence_reports_select".
 */
export interface IntelligenceReportsSelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ethnography_and_archaeology_select".
 */
export interface EthnographyAndArchaeologySelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "government_reports_select".
 */
export interface GovernmentReportsSelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternative_heritages_select".
 */
export interface AlternativeHeritagesSelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alternative_archival_heritages_select".
 */
export interface AlternativeArchivalHeritagesSelect<T extends boolean = true> {
  internalName?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  image?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo: number | Media;
  nav?:
    | {
        id?: string | null;
        label?: string | null;
        link?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  logo: number | Media;
  nav?:
    | {
        label?: string | null;
        link?: string | null;
        id?: string | null;
      }[]
    | null;
  copyrightNotice: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  nav?:
    | T
    | {
        id?: T;
        label?: T;
        link?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  nav?:
    | T
    | {
        label?: T;
        link?: T;
        id?: T;
      };
  copyrightNotice?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}